[build]
builder = "dockerfile"
dockerfilePath = "apps/api/Dockerfile"

[deploy]
startCommand = "sh -c 'cd apps/api && prisma migrate deploy && prisma db seed && node dist/main'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "archaos-api"
